config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "/mybookings", to: "pages#mybookings", as: :mybookings
  get "/mylistings", to: "pages#mylistings"

  # resources :bookings

  resources :spaces do
    resources :bookings
     # get "/mybookings", to: "pages#mybookings", as: :mybookings, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :space
  belongs_to :user
  validates_presence_of :date
  validate :future_event

  private

  def future_event
    errors.add(:date, "Can't be in the past!") if date < Time.now
  end
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates_presence_of :name, :location, :price, :category
  mount_uploader :photo, PhotoUploader
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  include PgSearch
  pg_search_scope :search_by_name_and_location,
    against: [:name, :location, :category],

    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :spaces
  has_many :bookings
  validates_presence_of :name, :email, :password
  validates :password, length: { minimum: 8, too_short: "Your password must be at least 8 characters long" }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # include Pundit
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Bookings.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @space = Space.find(params[:space_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.space = Space.find(params[:space_id])
    @booking.user = current_user

    # raise

    if @booking.save
      redirect_to mybookings_path
    else
     @booking = Booking.new
     @space = Space.find(params[:space_id])
     render :new
    end
  end

  def edit
    @space = Space.find(params[:space_id])
  end

  def update
    @booking.update(booking_params)
    redirect_to mybookings_path
  end

  def destroy
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:home, :spaces, :space]

  def home
    @user = current_user
  end

  def mylistings
    @user = current_user
    @spaces = Space.where(user_id: @user.id)
    @space_bookings = Space.where(user_id: @user.id).sort_by { |space| space.bookings.count }
    # @bookings = @spaces.select { |space| Booking.where(space_id: space.id) }
  end

  def mybookings
    @user = current_user
    @bookings = Booking.where(user_id: @user.id)
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  before_action :find_space, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = " \
        spaces.name @@ :query \
        OR spaces.location @@ :query \
        AND spaces.category @@ :category \
      "
      @spaces = Space.where(sql_query, category: "%#{params[:category]}%", query: "%#{params[:query]}%")
      @spaces_markers = @spaces.where.not(latitude: nil, longitude: nil)
    else
      @spaces = Space.all
      @spaces_markers = Space.where.not(latitude: nil, longitude: nil)
    end

    @markers = @spaces_markers.map do |space|
      {
        lng: space.longitude,
        lat: space.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { space: space })
      }
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    if @space.save
      redirect_to space_path(@space.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @space.update(space_params)
    redirect_to mylistings_path
  end

  def destroy
    @space.delete
    redirect_to mylistings_path
  end

  private

  def find_space
    @space = Space.find(params[:id])
  end

  def space_params
    params.require(:space).permit(:name, :location, :price, :category, :user_id, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<div class="flex-wrapper">
  <div class="container">
    <div class="booking-listing-header">
      <h1>Edit your booking</h1>
    </div>
    <div class="card-product">
      <%= image_tag @space.photo.url %>
      <div class="card-product-infos">
        <h2 class="booking-card-title"><%= @space.name %></h2>
        <h4 class="booking-card-location"><%= @space.location %></h4>
        <p class="booking-card-date booking-info"><strong>BOOKED DATE</strong> </br> <%= @booking.date %></p>
        <p class="booking-card-host booking-info"><strong>BOOKING ID</strong> </br> REFX<%=@booking.id %></p>
        <div class="form-box change-date">
          <%= simple_form_for [@space, @booking] do |f| %>
          <%= f.input :date, label: "Select new date", class: "small-input-form"%>
          <%= f.submit "Confirm new date", class: "btn btn-primary small-text" %>
          <% end  %>
        </div>
      </div>
    </div>
  </div>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>

<ul>
  <% @bookings.each do |booking| %>
  <li>
    <%= booking.date %>
  </li>
    <% end %>
</ul>

app/views/bookings/new.html.erb
<div class="container">
  <h1>Confirm your booking</h1>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="form-box">
        <h2>Select your date!</h2>
        <%= simple_form_for [@space, @booking] do |f| %>
          <%= f.input :date %>
          <%= f.submit "Book Now!", class: "btn btn-primary" %>
        <% end  %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h1><%= @space.name %></h1>

<ul>
  <li>
    <p>Date: <%= @booking.date %></p>
  </li>
  <li>
    <p>Location: <%= @space.location %></p>
  </li>
  <li>
    <p>Category: <%= @space.category %></p>
  </li>
  <li>
    <p>Price: <%= @space.price %></p>
  </li>
</ul>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <br><br>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="home-title">
  <div class="head" style="background-image: url(<%= image_path 'spacedesignedit.jpg' %>)">
    <div class=form-text>
      <div class="company-text">
        <h1>Find the perfect space for your next Get Together</h1>
      </div>
      <div class=home-form>
      <%= form_tag(spaces_path, method: 'get') do %>
      <% categories = ["Dinner Party", "Pool Party", "Cocktail Party", "Movie Night", "Birthday", "Family"] %>
      <%= select_tag :category, options_for_select(categories)%>
      <%#= collection_select :category %>
      <%= text_field_tag :query, params[:query], placeholder: 'Location or Name'%>
      <%= submit_tag 'Search'%>
      <% end %>
      </div>
    </div>
    </div>
  </div>
</div>
<div class="booking-instruction">
  <div class="text-center">
    <h2>How to Book?</h2>
  </div>
  <div class="row">
    <div class="col-md-4 col-xs-6">
      <%= image_tag 'magnifyingglass.png', class: 'instruction-img' %>
      <div class=text-center>
        <h2>Find your space</h2>
        <p>Filter your search to find a space whenever and wherever you are</p>
      </div>
    </div>
    <div class="col-md-4 col-xs-6">
      <%= image_tag 'calendar.png', class: 'instruction-img' %>
      <div class="text-center">
        <h2>Set a date</h2>
        <p> Set a date to find a space that suits your need</p>
      </div>
    </div>
    <div class="col-md-4 col-xs-6">
      <%= image_tag 'handshake.png', class: 'instruction-img' %>
      <div class="text-center">
        <h2>Make a space</h2>
        <p>Have a space to rent? Go ahead and list it on our website.</p>
      </div>
    </div>
  </div>
</div>
<div class="search-card">
  <div class=text-center>
    <h2>Find places for your next event</h2>
    <h3>We provide, You decide</h3>
  </div>
  <div class="container">
  <div class="row">
    <div class="col-md-4 col-xs-6">
      <a href="">
        <%= image_tag 'dinnerparty.jpg', class: 'card-img' %>
        <h3>Dinner Party</h3>
      </a>
    </div>
    <div class="col-md-4 col-xs-6">
      <a href="">
        <%= image_tag 'poolparty.jpg', class: 'card-img' %>
        <h3>Pool Party</h3>
      </a>
    </div>
    <div class="col-md-4 col-xs-6">
      <a href="">
        <%= image_tag 'cocktailparty.jpg', class: 'card-img' %>
        <h3>Cocktail Party</h3>
      </a>
    </div>
    <div class="col-md-4 col-xs-6">
      <a href="">
        <%= image_tag 'movienight.jpg', class: 'card-img' %>
        <h3>Movie Night</h3>
      </a>
    </div>
    <div class="col-md-4 col-xs-6">
      <a href="">
        <%= image_tag 'birthday.jpg', class: 'card-img' %>
        <h3>Birthday Party</h3>
      </a>
    </div>
    <div class="col-md-4 col-xs-6">
      <a href="">
        <%= image_tag 'family.jpg', class: 'card-img' %>
        <h3>Family Gatherings</h3>
      </a>
    </div>
  </div>
  </div>
</div>

app/views/pages/mybookings.html.erb
<div class="container">
  <div class="booking-listing-header">
    <h1>Your bookings</h1>
  </div>
  <% @bookings.each do |booking| %>
    <div class="card-product">
      <%= image_tag booking.space.photo.url %>
      <div class="card-product-infos">
        <h2 class="booking-card-title"><%= booking.space.name %></h2>
        <h4 class="booking-card-location"><%= booking.space.location %></h4>
        <p class="booking-card-date booking-info"><strong>BOOKED DATE</strong> </br> <%= booking.date %></p>
        <p class="booking-card-host booking-info"><strong>BOOKING ID</strong> </br> REFX<%= booking.id %></p>
        <%= link_to 'Change date', edit_space_booking_path(booking.space, booking), class: "booking-card-button"%>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/mylistings.html.erb
<div class="container">
  <div class="booking-listing-header">
    <h1>Your listings</h1>
  </div>
  <% @space_bookings.reverse.each do |space| %>
    <div class="card-listing">
      <div class="image-edit-block">
        <%= image_tag space.photo.url, class: "listing-img"%>
        <%= link_to 'Edit listing', edit_space_path(space.id), class: "listing-card-button"%>
      </div>
      <div class="card-product-listings">
        <h2 class="listing-card-title"><%= space.name %></h2>
        <h4 class="listing-card-location"><%= space.location %></h4>
        <h4 class="listing-card-bookings">Upcoming bookings</h4>
        <div class="bookings-for-listing-container">
          <% if space.bookings.empty? %>
            <p>Sorry, you don't have any bookings for this listing yet</p>
          <% end  %>
          <% space.bookings.each do |booking| %>
            <div class="booking-for-listing-card">
              <p><strong>BOOKED ON:</strong></br> <%= booking.date %></p>
              <%= link_to "Manage booking", edit_space_booking_path(booking.space, space), class: "booking-button" %>
            </div>
          <% end  %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links text-center">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>

    <div class="footer1">
      Get-Together © 2019 | Powered by Le Wagon!
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "gettogetherlogo.png", height: 100 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right d-lg-flex d-md-flex d-xs-none d-sm-none">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "List Your Space", new_space_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% if current_user.spaces.present? %>
        <%= link_to "My Listings", mylistings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end  %>
      <% if current_user.bookings.present? %>
        <%= link_to "My Bookings", mybookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <i class="fas fa-bars" data-toggle="dropdown" class="avatar dropdown-toggle" id="navbar-wagon-menu"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "My Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "List Your Space", new_space_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item d-xs-flex d-sm-flex d-md-none d-lg-none">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/spaces/_infowindow.html.erb
<h1><%= space.name %></h1>

<ul>
  <li>
    <p>Location: <%= space.location %></p>
  </li>
  <li>
    <p>Price: <%= space.price %></p>
  </li>
</ul>

app/views/spaces/create.html.erb
<h1>Spaces#create</h1>
<p>Find me in app/views/spaces/create.html.erb</p>

app/views/spaces/destroy.html.erb
<h1>Spaces#destroy</h1>
<p>Find me in app/views/spaces/destroy.html.erb</p>

app/views/spaces/edit.html.erb
<h1><%= @space.name %></h1>

<h3>Edit form</h3>
<%= simple_form_for(@space) do |f| %>
  <%= f.input :name %>
  <%= f.input :location %>
  <%= f.input :category %>
  <%= f.input :price  %>
  <%= f.submit "Edit your listing", class: "btn btn-primary" %>
<% end  %>

app/views/spaces/index.html.erb
<div class="main-container">
  <div class="card-container">
    <div class="search-bar">
      <%= form_tag(spaces_path, method: 'get') do %>
      <% categories = ["Dinner Party", "Pool Party", "Cocktail Party", "Movie Night", "Birthday", "Family"] %>
      <%= select_tag :category, options_for_select(categories)%>
      <%#= collection_select :category %>
      <%= text_field_tag :query, params[:query], placeholder: 'Location or Name'%>
      <%= submit_tag 'Search'%>
      <% end %>
    </div>
  <div class="box-header">
    <h1>Showing <%= params[:category] %> spaces in <%= params[:query] %></h1>
  </div>
  <div class="container-margin">
    <div class="row">
      <% @spaces.each do |space| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <%= link_to space_path(space.id), class: "card-link" do %>
            <div class="card-trip">
              <%= image_tag space.photo.url %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= space.name %></h2>
                  <p><%= space.location %></p>
                </div>
                <h2 class="card-trip-pricing">$<%= space.price %></h2>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/spaces/new.html.erb
<div class="banner">
  <div class="container1">
    <h2>Rent <strong>your space.</strong> Make more money.</h2>
    <br>
    <div class="para">
      <p>Whether you're a rooftop bar, art gallery, garden space with plenty of space
    to spare, Get-Together is the platform for you to promote your venue at.</p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="form-box">
        <h2>List your space</h2>
        <%= simple_form_for(@space) do |f| %>
          <div class="form-inputs">
            <%= f.input :name, label: 'Space name' %>
            <%= f.input :location, label: 'Address' %>
            <%= f.input :category, label: 'Space type' %>
            <%= f.input :price %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.submit "Add your listing", class: "btn btn-primary" %>
          </div>
        <% end  %>
      </div>
    </div>
  </div>
</div>

app/views/spaces/show.html.erb
<div class="banner" style="background-image: url(<%= image_path @space.photo %>);">
  <div class="banner-content">
  </div>
</div>
<br>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 center-text">
      <h2><%= @space.name %></h2>
      <br>
      <div class="container-sections">
        <div class="border-table">
          <p><strong>Location</strong></p> <hr> <br>

          <p><%= @space.location %></p>
        </div>
        <div class="border-table">
          <p><strong>Price</strong>   <hr><br>
            <%= @space.price %></p>
          </div>
          <div class="border-table">
            <p><strong>Category</strong> <hr> </p> <br>
            <div class="icons-container">
              <div class="icon-text-center">
                <i class="fas fa-cocktail fa-2x"></i>
                <p>Cocktail</p>
              </div>
              <div class="icon-text-center">
                <i class="fas fa-utensils fa-2x"></i>
                <p>Dining</p>
              </div>
              <div class="icon-text-center">
                <i class="fas fa-child fa-2x"></i>
                <p>Kid friendly</p>
              </div>
            </div>

          </div>
        </div>

      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="form-box">
          <h2>Select your date!</h2>
          <%= simple_form_for [@space, @booking] do |f| %>
          <%= f.input :date %>
          <%= f.submit "Book Now!", class: "btn btn-primary" %>
          <% end  %>
        </div>
      </div>
    </div>
  </div>

app/views/spaces/show_back.html.erb
<div class="banner" style="background-image: url(<%= image_path @space.photo %>);">
  <div class="banner-content">
  </div>
</div>
<br>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8">
      <h2><%= @space.name %></h2>
      <p>Location: <%= @space.location %></p>
      <p>Category: <%= @space.category %></p>
      <p>Price: <%= @space.price %></p>
      <hr>
      <div class="icons-container">
        <div class="icon-text-center">
          <i class="fas fa-cocktail fa-2x"></i>
          <p>Cocktail</p>
        </div>
        <div class="icon-text-center">
          <i class="fas fa-utensils fa-2x"></i>
          <p>Dining</p>
        </div>
        <div class="icon-text-center">
          <i class="fas fa-child fa-2x"></i>
          <p>Kid friendly</p>
        </div>
        <div class="icon-text-center">
          <i class="fas fa-user fa-2x"></i>
          <p>Max 25 Pax</p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class="form-box">
        <h2>Select your date!</h2>
        <%= simple_form_for [@space, @booking] do |f| %>
          <%= f.input :date %>
          <%= f.submit "Book Now!", class: "btn btn-primary" %>
        <% end  %>
      </div>
    </div>
  </div>
</div>

app/views/spaces/update.html.erb
<h1>Spaces#update</h1>
<p>Find me in app/views/spaces/update.html.erb</p>